services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: webxrapi
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: webxrclient
    ports:
      - "3000:80"